### ISSUE TITLE
Possibility to add new teams/players?

### ISSUE THREAD

**Issue by ghost** [Aducj1910/IPLSimulator#2]
This is not an actual issue. 

I am enjoying the simulator a lot. I am trying to make adjustments so that new teams/players can be added. 
I have tried updating the following:

1. playerInfoProcessed.json;
2. added a new teams .txt file
From what I can see, nothing else should require updating? Please correct me if I'm wrong.

I have also been attempting to add some delays in between each delivery. 

I've added these to the delivery class but unable to get the delays between each innings. 

Do you have any suggestions here?

Thanks again, great stuff
@Aducj1910

**Comment by Aducj1910** [comment]
Hi! I am working on a UI, I have already implemented a way to add new teams and there's also a delay
I am working on adding a way to add new players and I will release the new version in a few weeks' time

Here are some screenshots
![image](https://user-images.githubusercontent.com/62986699/126104327-8f09ff92-63af-4a56-9f4f-8a8a72bfbfbf.png)
![image](https://user-images.githubusercontent.com/62986699/126104368-3783cf4d-935e-4fbf-91eb-e822416c03a5.png)
![image](https://user-images.githubusercontent.com/62986699/126104539-2288f04b-9273-4f24-96a7-fe18809dbed8.png)

I am also working on updates to the algorithm (like how sometimes batsmen start bowling)

**Comment by Aducj1910** [comment]
Apart from that, You have to edit this file - https://github.com/Aducj1910/IPLSimulator/blob/master/teams/teams.json (the json, not the txt)
to add new teams, make sure that the player has played in the IPL before and you can pick the name from the playerInfoProcessed.json file

Edit: about the delay, add a time.sleep under both `def delivery` functions

eg.
     `time.sleep(2) #adds 2 second delay`
     add this under the def delivery(bowler, batter, over): line

**Comment by ghost** [comment]
Thanks for your comments about the delay and adding new teams.

It's looking good based on your screenshots. Excited to see where it goes.

**Comment by Aducj1910** [comment]
> Thanks for your comments about the delay and adding new teams.
> 
> It's looking good based on your screenshots. Excited to see where it goes.

Thanks!
Feel free to email me at adish1910@gmail.com if you have any more questions or issues with the team adding, I'd be glad to help you out!
